spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:movies-battle
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platorm: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

omdbapi:
  url: http://www.omdbapi.com
  apikey: 2e300fd8
  movies: Nomadland,Bohemian Rhapsody,Parasite,The Shape of Water,Moonlight,The Revenant,12 years a slave,Django Unchained,the Social network