spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:movies-battle
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platorm: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2